FROM python:3

RUN git clone -b feature/connection-util https://github.com/IntegrCiTy/obnl.git
# RUN git clone -b demo https://github.com/IntegrCiTy/obnl.git
# RUN git clone https://github.com/IntegrCiTy/obnl.git

RUN pip install --no-cache-dir -r obnl/requirements.txt
RUN cd obnl && python setup.py install

RUN pip install redis docopt

RUN mkdir /home/project
WORKDIR /home/project

ENV PYTHONDONTWRITEBYTECODE=1

ENTRYPOINT ["python"]
