FROM python:3

RUN git clone -b feature/logger https://github.com/IntegrCiTy/obnl.git
# RUN git clone https://github.com/IntegrCiTy/obnl.git

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r obnl/requirements.txt
RUN cd obnl && python setup.py install

RUN pip install docopt

RUN mkdir /home/project
WORKDIR /home/project

ADD server.py $WORKDIR

ENTRYPOINT ["python", "server.py"]